name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      

      # Run tests with coverage
      - name: Run tests with coverage
        run: npm test -- --coverage

        # Debug: List files in the current directory
      - name: Debug - List files
        run: ls -al

      

      # Debug: List files in the coverage directory
      - name: Debug - List coverage files
        run: ls -al coverage

        # Debug: Print the content of the lcov.info file
      - name: Debug - Show lcov.info content
        run: cat coverage/lcov.info

      # Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        run: npm install -g coveralls && coveralls debug < coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
